Repository wecode-bootcamp-korea/49-3rd-Connection-backend, pull requests merged in 2023-10, with the labels that each got.

#7 Feature/productList
  .env
  .env.sample
  .env.test
  .env.test.sample
  .gitignore
  app.js
  db/schema.sql
  package-lock.json
  package.json
  server.js
  src/controllers/index.js
  src/controllers/productController.js
  src/middleware/auth.js
  src/models/builder.js
  src/models/dataSource.js
  src/models/index.js
  src/models/productDao.js
  src/routers/index.js
  src/routers/productRouter.js
  src/services/index.js
  src/services/productService.js
  src/utils/throwError.js
  tests/product.test.js
Labels: 리뷰 진행 중

#11 Feature/users
  .env
  .env.sample
  .env.test
  .env.test.sample
  .gitignore
  app.js
  db/migrations/20231015082323_modify_users_table.sql
  db/migrations/20231015102315_modify_users_table2.sql
  db/schema.sql
  package-lock.json
  package.json
  server.js
  src/controllers/index.js
  src/controllers/userController.js
  src/middleware/auth.js
  src/models/index.js
  src/models/userDao.js
  src/routers/index.js
  src/routers/userRouter.js
  src/services/index.js
  src/services/userService.js
  src/utils/errorHandler.js
  src/utils/keyCheck.js
  src/utils/throwError.js
  tests/user.test.js
Labels: 수정 요청

#8 CREATE: product main
  .env.test
  app.js
  server.js
  src/controllers/index.js
  src/controllers/productController.js
  src/models/builder.js
  src/models/dataSource.js
  src/models/productDao.js
  src/routers/productRouter.js
  src/services/productService.js
  tests/product.test.js
Labels: 멘토 리뷰 요청

#12 Feature/orders
  .env.test
  db/migrations/20231020071816_create_points_in-usersTable.sql
  package.json
  src/controllers/index.js
  src/controllers/orderController.js
  src/models/index.js
  src/models/orderDao.js
  src/routers/index.js
  src/routers/orderRouter.js
  src/services/index.js
  src/services/orderService.js
  src/utils/errorHandler.js
  tests/order.test.js
Labels: 멘토 리뷰 요청, 완료
